### ISSUE TITLE
Hugo errors out with symlinks not allowed in this filesystem

### ISSUE THREAD

**Issue by lobopraveen** [lobopraveen/praveenlobo.com#74]
upgrading Hugo from 0.62.2 to 0.74.3 broke the build with the following error:
```bash
[praveenlobo.com]$ hugo server
Built in 904 ms
Error: Error copying static files: symlinks not allowed in this filesystem
```

Some version after the 0.62.2 is not allowing the symlinks that is employed to [de-duplicate the media](https://praveenlobo.com/blog/hugo-static-site-on-github-customizations/#de-duplicating-the-media).

**Comment by lobopraveen** [comment]
Project developer says that symlink handling has changed in [0.56.0](https://github.com/gohugoio/hugo/releases/tag/v0.56.0). I'm not sure if it is what is causing the issue here because the symlinks worked just fine in 0.62.2

**Comment by lobopraveen** [comment]
This issue was fixed by using mount module to mount the directory instead of symlinking it. You can refer to the commit 0bd4ae8.

```toml
[module]
    [[module.mounts]]
        source = "docs/media"
        target = "static/media"
```

**Comment by lobopraveen** [comment]
Mounts module ignores the content already present in the static directory which is causing even bigger issues! Reopening....

**Comment by phxnsharp** [comment]
In case others find this issue, the answer is that as soon as you have a module mount into static, it ignores the staticDir directive. But you can re-create the necessary mounts yourself:

```toml
[module]
    [[module.mounts]]
        source = "docs/media"
        target = "static/media"
    [[module.mounts]]
        source = "static"
        target = "static"
```
